### PR TITLE
Added support for more than one handler

### PR DESCRIPTION
**Pull request by mbhinder**
This commit changes the match function for handlers to return more than
one handler in the mux.

The ServeDNS function iterates over all the handlers and buffers any
messages written onto the wire by them. The message from the final
handler is combined with the other messages and finally written out onto
the wire.

@variadico  @cpk55  @Arvinderpal @y0ssar1an

### CODE REVIEW

**Comment by variadico** [comment]
So, I noticed miekg said,

> I think another way to do is to have 1 handler for foo.com (or .) and re-implement the specific handling you'll need.
Also I seem to remember that I've implement the surrounding bits that you can define your own mux and do whatever you like.

Did we still want to merge this or are we gonna try doing it another way?

**Comment by mbhinder** [comment]
His approach will require a big refactor to the continuum code. I'm inclined to get this merged. It solves our use case pretty well.

**Comment by variadico** [comment]
Cool, okay. Just checking. Let me checkout this code now.

**Comment by variadico** [comment]
Seems fine. LGTM.

**Comment by mbhinder** [comment]
Verified system tests pass using this change, merging.

**Pull request merged**
